name: "Claude Terminal"
description: "Terminal interface for Anthropic's Claude Code CLI"
version: "1.0.0"
slug: "claude_terminal"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/anthropics/claude-code"
ingress: true
ingress_port: 7681
panel_icon: mdi:code-braces
panel_title: "Claude Terminal"
panel_admin: true
ports:
  7681/tcp: 7681
ports_description:
  7681/tcp: "Web terminal (not required for ingress)"
options: {}
schema: {}
map:
  - config:rw
  - addons:rw
startup: services
webui: http://[HOST]:[PORT:7681]/